# Generated by Django 4.0.3 on 2022-04-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_review',
            field=models.CharField(default='http://127.0.0.1:8000/api/review/', max_length=255),
        ),
    ]
